### ISSUE TITLE
Week 3: Your times up....

### ISSUE THREAD

**Issue by mtthwm** [mtthwm/Intro-To-Serverless#42]
Week 3 Step 4 ⬤⬤⬤⬤◯◯◯◯◯ | 🕐 Estimated completion: 10-20 minutes

# Your time's up....
*This week, you will be going through steps to create a Timer Trigger Function delete all files in your Blob storage container every 5 minutes. This assists us in automated cleanups for our storage container and removing outdated files that users no longer need.*

## ✅  Task:

- [x]  ***1:*** Create a Timer Trigger Function to delete all files in your Blob storage container every 5 minutes.
- [x]  ***2:*** Test your new Timer Trigger Function
- [x]  ***3:*** Commit your new code to the `bunnimage` branch!
- [x]  ***4:*** Comment an expression that tells the Timer Trigger to run everyday at 6:23 AM.

> 💡 **Tip:** [Cron expressions](https://crontab.guru/) might help you with the last task.

## 🚧 Test Your Work

To test your work, use Postman to send a POST request with an image to your previous HTTP trigger function that will save your file within your blob. Recall that a successful save of your file will cause you to see a response similar to the below:

```JSON
{
  "body" : "File Saved"
}
```

You should also double check that your file has been saved by navigating to your storage blobs.

Now run your timer trigger function using `func start` and re-check your storage blobs - they should be gone. Your logs notifying you of the blobs' deletions should also be displayed in your trigger function's console. 

> 💡 Yay! This means your timer trigger function worked.

---

## 1: Create your Timer Trigger Function

First, we'll need to create a new Azure Function that runs on a schedule with the Timer Trigger template.

1.  Create a new Function, naming it `bunnimage-timer` and select `Timer trigger`

![image](https://user-images.githubusercontent.com/69332964/122659834-c6058380-d149-11eb-93fd-2745caab4c57.png)

2. Leave the `Schedule` as `0 */5 * * * *` to have the function be triggered [every 5 minutes](https://crontab.guru/every-5-minutes).

![image](https://user-images.githubusercontent.com/69332964/122659854-e6354280-d149-11eb-976e-02d3566bf94a.png)

3. Press enter on your keyboard.

## 2: Code your Timer Trigger Function

* Reference your container string from your environment secrets
* Reference the `@azure/storage-blob` package
* Reference your account name

<details>
<summary>❓ How do I create the global variables above?</summary>

To reference the `@azure/storage-blob` package:

```js
const { BlobServiceClient } = require("@azure/storage-blob");
```

To reference your connection string and account name:

```js
const connectionstring = process.env["AZURE_STORAGE_CONNECTION_STRING"];
const account = "YOUR_STORAGE_ACCOUNT_NAME";
```

</details>

To **delete all the blobs** in the container, you can first list all the blobs, then loop through deleting each one as you go.

<details>
<summary>❓ How do I delete a blob?</summary>

Use the [`deleteBlob`](https://docs.microsoft.com/en-us/javascript/api/@azure/storage-blob/containerclient?view=azure-node-latest#@azure-storage-blob-containerclient-deleteblob) method from the Azure SDK! Here's an example:
```js
await blobContainerClient.deleteBlob(filename)
```

</details>

<details>
<summary>❓ How do I call the `deleteBlob` function within `module.exports` and loop through existing blobs?</summary>

Exactly like the beginning of your `deleteBlob` function, you'll want to:
1. Create a `BlobServiceClient` object using your connection string.
2. Create a variable that references the name of the container that contains the file you want to delete.
3. Fetch the container with that name.

```js
const blobServiceClient = await BlobServiceClient.fromConnectionString(connectionstring);
const deletecontainer = "images";
const blobContainerClient = await blobServiceClient.getContainerClient(deletecontainer);
```

Now you'll want to use the [`listBlobsFlat`](https://docs.microsoft.com/en-us/javascript/api/@azure/storage-blob/listblobsflatsegmentresponse?view=azure-node-latest) function to retrieve a reference to an enumeration of your blobs. Loop through these blobs, and delete each one.

```js
for await (const blob of blobContainerClient.listBlobsFlat()) {
    context.log(`Deleting blob name ${blob.name}`);
    
    // a line of code here should access the blob's name and use `deleteBlob()` to delete the blob!
}
```

You can also add a log after your for loop that notifies you that all the blobs have been deleted.

```js
context.log("Just deleted your blobs!")
```

</details>

## 📹 Walkthrough Video
[![walkthrough video](https://img.youtube.com/vi/lWm8hbF2BoE/0.jpg)](https://www.youtube.com/watch?v=lWm8hbF2BoE)

**Comment by mtthwm** [comment]
23 6 * * *

**Comment by emsesc** [comment]
23 6 * * *
