### ISSUE TITLE
Start Coding!

### ISSUE THREAD

**Issue by mtthwm** [mtthwm/Intro-To-Serverless#71]
Final Project Step 5 ⬤⬤⬤⬤⬤◯ | 🕐 Estimated completion: 1-5 hours

## ✅  Task:

- [ ] Based on your schedule determined in "timeline.md", find the first issue you need to work on and begin your first task
- [ ] 🚀 Close the issue when you have completed
- [ ] 🚀 Commit your changes to the `final-project` branch, make a pull request, and merge it

### Developing the first component

> :bulb: Start small then build big!

Let's look back at the advice we got from the previous step: "start small then build big." Your goal is to get something working - not to developing your final project in 1 week.
* Begin by just having one working component of the project. Ex:
  * Press a button on your webpage and receive information
  * Create a working Azure Function that can return information
* After that's complete and tested, begin building onto that with more and more features!

### Committing code

:exclamation: Best practices for commiting code is to **commit it constantly**. Any time you make a change, commit the change.

#### :question: Why?
Every time you develop something that works, **commit and push it immediately**. This is so that if/when your code breaks due to a bug, you can easily revert back to the latest working commit. It also shows a history of how you have worked on your code.

> :bulb: **Tip:**: You want to name the commit accurately to the changes you have made so that they are easy to search through later.

**Comment by mtthwm** [comment]
closed via oauth
